### PR TITLE
Make logging behave

### LINKED ISSUE #11: anyconfig should not attach its own logging hanlers
The library should not attach a new handler to a logger implicitly. Anyconfig does that during import which is very nasty:

https://docs.python.org/2/howto/logging.html#configuring-logging-for-a-library

>Note It is strongly advised that you _do not add any handlers other than `NullHandler` to your library’s loggers_. This is because the configuration of handlers is the prerogative of the application developer who uses your library. The application developer knows their target audience and what handlers are most appropriate for their application: if you add handlers ‘under the hood’, you might well interfere with their ability to carry out unit tests and deliver logs which suit their requirements.

### PR DESCRIPTION
**Pull request by wbolster**
This PR removes all custom logging magic, and changes the behaviour to
the standard way of logging for Python libraries.

In short, instead of magic global loggers and setting global
configuration (so that applications experience problems), all logging
calls are simply emitted on module-level loggers. It's up to the
application to route these messages somewhere useful by configuring
handlers and setting levels.

Fixes #11.

### CODE REVIEW

**Comment by ssato** [comment]
Thanks a lot for the fix. You're right. Merged as it is.

**Comment by wbolster** [comment]
Great @ssato. Any chance you could publish a new release with this fix? Thanks!

**Comment by ssato** [comment]
I've just released the new version that fix was included. Please let me know if you any issues w/ it.
And, again, thanks for the fix!

**Comment by wbolster** [comment]
Awesome, thanks @ssato.

**Pull request merged**
